services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: contacts-db
    environment:
      MYSQL_ROOT_PASSWORD: example 
      MYSQL_DATABASE: example_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: contacts-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example 
      DB_NAME: example_db
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    container_name: contacts-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  db_data: